version: '3'
services:
  db:
    image: postgres:latest
    container_name: mst__pg_db
    hostname: mst__pg_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db
    ports:
      - 192.168.141.1:5432:5432
    volumes:
      - ./docker/storage/pgdb:/var/lib/postgresql/data

  db_lib:
    image: postgres:latest
    container_name: mst__pg_db_lib
    hostname: mst__pg_db_lib
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db_lib
    ports:
      - 192.168.141.1:54321:5432
    volumes:
      - ./docker/storage/library/pgdb:/var/lib/postgresql/data

#  prometheus:
#    image: prom/prometheus:latest
#    container_name: prometheus
#    hostname: prometheus
#    volumes:
#      - ./docker/dev/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
#      - ./docker/storage/prometheus:/prometheus
#    command:
#      - '--config.file=/etc/prometheus/prometheus.yml'
#      - '--storage.tsdb.path=/prometheus'
#    ports:
#      - 9090:9090
#
#  grafana:
#    image: grafana/grafana:latest
#    container_name: grafana
#    hostname: grafana
#    links:
#      - prometheus:prometheus
#    volumes:
#      - ./docker/storage/grafana:/var/lib/grafana
#    environment:
#      - GF_SECURITY_ADMIN_USER=root
#      - GF_SECURITY_ADMIN_PASSWORD=root
#      - GF_USERS_ALLOW_SIGN_UP=false
#    ports:
#      - 3000:3000

  storage:
    build:
      context: ./storage/docker/dev
      dockerfile: nginx.docker
    container_name: mst__storage_nginx
    hostname: mst__storage_nginx
    volumes:
      - ./storage:/app
    ports:
      - 192.168.141.1:8081:80
  storage-ftp:
    image: stilliard/pure-ftpd
    container_name: mst__storage_ftp
    hostname: mst__storage_ftp
    ports:
      - 192.168.141.1:21:21
      - 192.168.141.1:30000-30009:30000-30009
    environment:
      PUBLICHOST: "192.168.141.1"
      FTP_USER_NAME: app
      FTP_USER_PASS: secret
      FTP_USER_HOME: /app
    volumes:
      - ./storage/public:/app

  mailer:
    image: mailhog/mailhog
    container_name: mst__mailer
    hostname: mst__mailer
    ports:
      - 192.168.141.1:8025:8025
      - 192.168.141.1:1025:1025

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.141.0/24