http:
  maxHeaderBytes: 1
  readTimeout: 20s
  writeTimeout: 10s
locale:
  default: "en" # support - en, ru

limiter:
  rps: 10
  burst: 20
  ttl: 10m

cache:
  ttl: 10s

#serviceName: library_service
#grpc:
#  port: :5052
#  development: true
#kafka:
#  brokers: [ "localhost:9092" ]
#  groupID: library_microservice_consumer
#  initTopics: true
#kafkaTopics:
#  authorCreate:
#    topicName: author_create
#    partitions: 10
#    replicationFactor: 1
#  authorCreated:
#    topicName: author_created
#    partitions: 10
#    replicationFactor: 1
#redis:
#  addr: "localhost:6379"
#  password: ""
#  db: 0
#  poolSize: 300
jaeger:
  enable: true
  serviceName: library_service
  hostPort: "localhost:6831"
  logSpans: false